### ISSUE TITLE
Add `Story` template

### ISSUE THREAD

**Issue by sleepylee** [nimblehq/git-template#16]
## Why

When a developer intends to use Github Project as their main backlog, it is common that they will use and open `Issue` as a feature story. At the moment, our templates do not support the `Story` template like we usually do in a real project:

```
## Why

Describe the idea of the user story as in what the motive of the user story is.

## Acceptance Criteria

List down how the user story will be tested and what criteria are necessary for the user story to be accepted.

## Design

(Optional) Add design screenshots or Figma links for UI/UX-related stories.

## Resources

(Optional) Add useful resources such as links to documentation, implementation ideas, or best practices.
```

Having this new template could avoid the confusion caused to a developer in case they have never written any tickets on a client project backlog.

Differentiate between an RFC template for the public to use vs the Story on the project backlog for the team to work on.
 
## Who Benefits?
Everyone

**Comment by olivierobert** [comment]
@sleepylee Good suggestion. The template needs to follow the team conventions: https://nimblehq.co/compass/product/backlog-management/user-stories/features/#description. The headings must be `h2` / `##` and there needs to be a fourth section for `Resources`.

**Comment by sleepylee** [comment]
@olivierobert I updated the template details accordingly

**Comment by rafayet-monon** [comment]
This is super helpful 💯
