### ISSUE TITLE
Improve git commit-msg hook

### ISSUE THREAD

**Issue by Goose97** [nimblehq/git-template#39]
## Why

After several day of using the new commit-msg hook introduced by https://github.com/nimblehq/git-template/issues/35. I have some suggestions:
1. The change I suggested, from:
```
git branch | grep '*'
```
to 
```
git rev-parse --abbrev-ref HEAD
```
unfortunately doesn't work when rewording a commit message during a interactive rebase session. The old way still works fine.
![image](https://github.com/nimblehq/git-template/assets/35915460/1cea2257-c8ce-4ceb-8b15-4d5c9f86fc25)

2. The [current implementation](https://github.com/nimblehq/git-template/blob/main/git/hooks/commit-msg#L24) will override the whole commit message. Which means for multi-lines commit messages, the message body will be lost. Maybe we could replace the first line only:
```
sed -i '' "1 s/^.*$/$PREFIX $FIRSTLINE/" "$1"
```

3. There's a case that developers might want to prefix with a different story than the one in the branch name. For example, when working with both UI and backend story in a same branch, one can have commits link to only one story, not both. The current behavior is:
```
Branch name: feature/sc-backend-test

# Wanted behaviour
Commit message: Test -> [sc-backend] Test

# Unwanted behaviour
Commit message: [sc-ui] Test -> [sc-backend] [sc-ui] Test
```

In case I manually include a story ID, I don't want the hook to prefix the commit message. Does this make any sense?

## Who Benefits?

Any developers who use the commit-msg hook in this repo

**Comment by Goose97** [comment]
cc @malparty since you introduced this hook

**Comment by malparty** [comment]
Thanks for these nice insights! :)

I would recommend creating a dedicated story for the 3rd item in the list, as it seems a bit more complex and edge case that the other items (which will be fast to implement I think) 🚀

**Comment by Goose97** [comment]
My bad, I forgot to mention that this issue supposes to serve as an RFC-ish. I'm not sure if all of these points I made should be address. After we agree what we should do, I'll extract them to separate issues.

So just to confirm, we will address all 3 points, right?
