### ISSUE TITLE
Handle cases when the branch not contains sc or gh story ids for git commit msg hook

### ISSUE THREAD

**Issue by tednguyendev** [nimblehq/git-template#42]
## Why

There are branches that do not have the `sc-` or `gh-`. They can be branch names that don't have any story ID (like, a branch to fix a very small `README.md` typo), or that they follow other conventions.

The current code is:

```bash
if [[ $BRANCH_NAME =~ ^sc-([0-9]+) ]]; then
  PREFIX="[${BASH_REMATCH[0]}]"
else
  # Extract only the digits after 'gh-' using parameter expansion
  PREFIX="[#${BRANCH_NAME##gh-}]"
fi
```

For these unexpected cases, they will fall into the `else` case which handles the branches that have `gh-`, which will be prefixed with `[#]`:

<img width="165" alt="CleanShot 2023-09-20 at 09 30 28@2x" src="https://github.com/nimblehq/git-template/assets/76901736/c701f111-6a9e-4cbc-a6b6-41afa4c22ea6">

I suggest ignoring these cases(not adding any prefix), instead of letting them fall into the `gh` case:

```bash
if [[ $BRANCH_NAME =~ ^sc-([0-9]+) ]]; then
  PREFIX="[${BASH_REMATCH[0]}]"
elif [[ $BRANCH_NAME =~ ^gh-([0-9]+) ]]; then
  # Extract only the digits after 'gh-' using parameter expansion
  PREFIX="[#${BRANCH_NAME##gh-}]"
else
  # No sc- or gh- prefix, do nothing
  exit 0
fi
```

## Who Benefits?

Any developers who use the commit-msg hook in this repo

**Comment by tednguyendev** [comment]
cc @malparty 🙇

**Comment by malparty** [comment]
No need to cc me. Just submit a PR xD

More seriously, at the moment I don't really mind the `[#]` in commits because if the branch does not have a story, it's usually not an important one ^^ But that's just my opinion. Other people needs and contributions are of course welcome 🚀

**Comment by tednguyendev** [comment]
I see. Yes, it makes sense. Seems like it's trivial hehe. Then I will visit this later!

Thank you!
